In [1]:
import pandas as pd

In [3]:
df = pd.read_json('popular.json')
df

,example_type,edit,Logical_Generalization,Compositionality_I,Compositionality_II,Subject_Aliasing,Relation_Specificity,Forgetfulness
0,popular,{'prompt': 'The name of the country of citizen...,[],[{'test_queries': [{'prompt': 'The name of the...,[],[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...
1,popular,{'prompt': 'The name of the country which Acad...,[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[],[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[]
2,popular,{'prompt': 'The name of the spouse of Ron DeSa...,[{'test_queries': [{'prompt': 'The names of th...,[{'test_queries': [{'prompt': 'The gender of t...,[],[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The gender of R...,[{'test_queries': [{'prompt': 'The name of the...
3,popular,{'prompt': 'The name of the child of Kanye Wes...,[],[],[],[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...
4,popular,{'prompt': 'The names of the siblings of Janic...,[{'test_queries': [{'prompt': 'The names of th...,[],[],[{'test_queries': [{'prompt': 'The names of th...,[{'test_queries': [{'prompt': 'The gender of J...,[{'test_queries': [{'prompt': 'The names of th...
...,...,...,...,...,...,...,...,...
880,popular,{'prompt': 'The gender of Jesse Plemons is tra...,[],[],[],[{'test_queries': [{'prompt': 'The gender of J...,[{'test_queries': [{'prompt': 'The name of the...,[]
881,popular,{'prompt': 'The name of the spouse of Osman I ...,[{'test_queries': [{'prompt': 'The names of th...,[{'test_queries': [{'prompt': 'The occupation ...,[],[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...
882,popular,{'prompt': '2022 FIFA World Cup qualification ...,[{'test_queries': [{'prompt': '1872 United Sta...,[],[],[],[{'test_queries': [{'prompt': '2022 FIFA World...,[]
883,popular,{'prompt': 'The name of the country which Aspi...,[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[],[],[],[]
884,popular,{'prompt': 'The name of the mother of Prince E...,[{'test_queries': [{'prompt': 'The names of th...,[{'test_queries': [{'prompt': 'The gender of t...,[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[{'test_queries': [{'prompt': 'The name of the...,[]